# -*- coding: utf-8 -*-
"""26_05_2023_4potok.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yD_ZycmMcdR-M2RF6JkvETFyo5QS7Rto
"""

print ("Привет мир")